import fs from "node:fs";
import path from "node:path";

const root = path.dirname(new URL(import.meta.url).pathname.replace(/^\/(.:)/, "$1"));

const papers = [
  ["01-foundations", "01-transformer", "1706.03762", "Attention Is All You Need", "Vaswani et al.", "attention turns words into context-aware representations", "A sentence is a meeting: every word can listen to every other word and decide whose message matters.", "Implement scaled dot-product attention; inspect Q, K, V shapes, masks, residual paths, and positional encodings.", "Derive softmax(QK^T/sqrt(d_k))V, explain the sqrt(d_k) variance control, and compare O(n^2 d) attention with recurrent computation.", "words --> embeddings --> [self-attention] --> contextual words --> prediction"],
  ["01-foundations", "02-bert", "1810.04805", "BERT: Pre-training of Deep Bidirectional Transformers", "Devlin et al.", "bidirectional pretraining and task adaptation", "BERT learns by filling blanks while looking both left and right, like solving a crossword with the whole clue visible.", "Use an encoder model for classification, search, and extraction; distinguish pretraining, fine-tuning, and inference.", "Analyze masked-language-model likelihood, representation transfer, token-level versus sequence-level heads, and pretrain/fine-tune distribution shift.", "unlabelled text --> mask words --> BERT encoder --> reusable representations --> task head"],
  ["01-foundations", "03-gpt3", "2005.14165", "Language Models are Few-Shot Learners", "Brown et al.", "autoregressive scaling and in-context learning", "GPT-3 behaves like an extremely well-read autocomplete system that can infer a task from examples placed in its prompt.", "Design zero-, one-, and few-shot prompts; separate context-window adaptation from weight updates; measure variance across prompt formats.", "Study autoregressive factorization, scaling effects, contamination, emergent-looking threshold behavior, and why in-context learning is not ordinary gradient training.", "instructions + examples --> next-token model --> continuation --> parsed task answer"],
  ["01-foundations", "04-scaling-laws", "2001.08361", "Scaling Laws for Neural Language Models", "Kaplan et al.", "predictable relationships among loss, data, model size, and compute", "Like recipes, bigger ovens, more ingredients, and more cooking time help only when they grow in sensible proportion.", "Use scaling curves for capacity planning; never compare models without tracking data, tokens, compute, and irreducible error assumptions.", "Reproduce power-law fits, examine compute-optimal frontiers and finite-data regimes, and test sensitivity to tokenizer, architecture, and dataset quality.", "compute budget --> choose model size + training tokens --> expected loss --> deployment trade-offs"],
  ["01-foundations", "05-chinchilla", "2203.15556", "Training Compute-Optimal Large Language Models", "Hoffmann et al.", "data-model balance under a fixed compute budget", "A very large student who reads too few books is undereducated; Chinchilla showed that many large models needed more training data.", "Estimate tokens-per-parameter, distinguish training-optimal from inference-optimal choices, and include serving volume in total-cost decisions.", "Compare the fitted loss model with Kaplan-style scaling, inspect isoFLOP curves, and reason about data repetition, quality, and extrapolation error.", "fixed FLOPs --> balance parameters and tokens --> lower loss --> different inference cost"],

  ["02-building", "06-rag", "2005.11401", "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks", "Lewis et al.", "combining a generator with retrieved evidence", "RAG is an open-book exam: the model first finds useful pages, then writes an answer using those pages.", "Build ingestion, chunking, embedding, retrieval, reranking, grounded generation, and citation evaluation as separately observable stages.", "Study latent-document marginalization, dense passage retrieval, parametric versus non-parametric memory, index staleness, and retrieval/generation error decomposition.", "question --> retriever --> evidence chunks --> generator --> cited answer"],
  ["02-building", "07-chain-of-thought", "2201.11903", "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models", "Wei et al.", "eliciting intermediate reasoning with demonstrations", "Showing worked examples can encourage a model to write intermediate steps before answering a hard question.", "Use demonstrations, structured outputs, verification, and hidden-answer tests; do not equate fluent reasoning text with faithful internal reasoning.", "Examine scale thresholds, task selection, self-consistency extensions, faithfulness critiques, and whether intermediate tokens provide useful test-time computation.", "problem + worked examples --> intermediate steps --> answer --> independent check"],
  ["02-building", "08-instructgpt", "2203.02155", "Training Language Models to Follow Instructions with Human Feedback", "Ouyang et al.", "instruction tuning and preference-based alignment", "Instead of only predicting text, the model is coached with examples and ranked responses so its behavior better matches human intent.", "Separate supervised demonstrations, preference data, reward modeling, and policy optimization; monitor helpfulness, safety, regressions, and annotator disagreement.", "Formalize the KL-regularized objective, reward-model identifiability, distribution shift, Goodhart effects, and the gap between stated and revealed preferences.", "base model --> demonstrations --> reward model --> optimized policy --> human evaluation"],
  ["02-building", "09-lora", "2106.09685", "LoRA: Low-Rank Adaptation of Large Language Models", "Hu et al.", "parameter-efficient adaptation", "Instead of rebuilding a whole machine, LoRA adds a small adjustable adapter that changes how the machine behaves.", "Choose target layers, rank, alpha, dropout, training data, and merge strategy; compare LoRA against prompting and full fine-tuning on quality and operations.", "Derive Delta W = BA, relate rank to an intrinsic subspace hypothesis, analyze initialization/scaling, and study expressivity versus optimization constraints.", "frozen weights W + small matrices B*A --> adapted layer --> task-specific model"],
  ["02-building", "10-react", "2210.03629", "ReAct: Synergizing Reasoning and Acting in Language Models", "Yao et al.", "interleaving thought, tool actions, and observations", "ReAct alternates between making a plan, using a tool, reading the result, and deciding what to do next.", "Define typed tools, bounded loops, timeouts, permissions, observation sanitization, and outcome traces; evaluate final success and unsafe attempts.", "Model the loop as a partially observable decision process; analyze credit assignment, tool-error recovery, prompt leakage, and planning versus reactive control.", "goal --> reason --> action --> observation --> reason --> ... --> answer"],

  ["03-evaluation-and-code", "11-mmlu", "2009.03300", "Measuring Massive Multitask Language Understanding", "Hendrycks et al.", "broad multiple-choice knowledge evaluation", "MMLU is a large cross-subject exam. It samples breadth, but an exam score is not the same as real-world competence.", "Run versioned prompts and scoring, report subject slices and uncertainty, detect contamination, and avoid using one aggregate as a product decision.", "Analyze construct validity, calibration, item response properties, contamination, multiple-choice artifacts, and longitudinal saturation.", "model --> subject exams --> per-domain scores --> uncertainty + error taxonomy"],
  ["03-evaluation-and-code", "12-truthfulqa", "2109.07958", "TruthfulQA: Measuring How Models Mimic Human Falsehoods", "Lin et al.", "truthfulness under common misconceptions", "A model can repeat a popular myth because it has seen it often; TruthfulQA asks whether it resists that temptation.", "Evaluate truth and informativeness separately; add domain experts, citations, refusal behavior, and adversarial paraphrases for business-critical claims.", "Study benchmark construction, judge dependence, imitation of misconceptions, truthfulness-helpfulness tension, and robustness to evaluator models.", "misleading question --> model answer --> truth judge + information judge --> failure analysis"],
  ["03-evaluation-and-code", "13-helm", "2211.09110", "Holistic Evaluation of Language Models", "Liang et al.", "multi-metric, scenario-based evaluation", "HELM is a vehicle inspection, not a single speed test: accuracy, robustness, fairness, efficiency, and other qualities are checked together.", "Create a scenario matrix of task, population, prompt, model, and metrics; record versions and costs; publish disaggregated results.", "Examine scenario coverage, metric correlations, missingness, reproducibility, normalization, and Pareto frontiers rather than scalar leaderboards.", "use case --> scenarios x metrics --> result matrix --> trade-off decision"],
  ["03-evaluation-and-code", "14-humaneval", "2107.03374", "Evaluating Large Language Models Trained on Code", "Chen et al.", "functional code generation measured by tests", "Instead of judging code by appearance, HumanEval runs hidden tests to see whether the program actually works.", "Sandbox generated code, understand pass@k, prevent test leakage, add security and maintainability checks, and never execute untrusted generations on a host.", "Derive the unbiased pass@k estimator, analyze sampling dependence and test adequacy, and distinguish synthesis, memorization, and specification ambiguity.", "prompt --> candidate programs --> isolated tests --> pass@k + error classes"],
  ["03-evaluation-and-code", "15-repobench", "2306.03091", "RepoBench: Benchmarking Repository-Level Code Auto-Completion Systems", "Liu et al.", "retrieval and completion across files", "Real software is a library, not one page. RepoBench checks whether a model finds the right related files before completing code.", "Index symbols and dependencies, measure retrieval and completion separately, respect repository licenses, and compare lexical, embedding, and structural retrieval.", "Study RepoBench-R/C/P, dependency-aware negatives, leakage, context allocation, retrieval recall versus generation accuracy, and language-specific effects.", "repository --> retrieve cross-file context --> complete code --> compile/test --> diagnose"],
  ["03-evaluation-and-code", "16-swe-bench", "2310.06770", "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?", "Jimenez et al.", "repository-level issue resolution with executable tests", "SWE-bench gives an agent a real bug report and a real codebase, then checks whether its patch fixes the bug without breaking other things.", "Pin containers and commits, separate localization from repair, track cost and attempts, inspect test patches, and report verified benchmark variants.", "Analyze task selection bias, test-patch validity, contamination, agent scaffolding effects, trajectory metrics, and the limits of pass/fail as a research signal.", "issue + repository --> explore --> edit --> test --> patch accepted or rejected"],

  ["04-agents-and-protocols", "17-camel", "2303.17760", "CAMEL: Communicative Agents for Mind Exploration of Large Scale Language Model Society", "Li et al.", "role-playing cooperation between agents", "Two agents are given complementary jobs and converse toward a goal, like a planner and an implementer working from a shared brief.", "Use explicit roles, termination rules, shared state, budgets, and evaluators; test whether extra agents outperform a strong single-agent baseline.", "Study role conditioning, inception prompting, coordination failure, correlated errors, simulation validity, and how interaction topology changes outcomes.", "human goal --> role A <--> role B --> artifacts --> evaluator"],
  ["04-agents-and-protocols", "18-autogen", "2308.08155", "AutoGen: Enabling Next-Gen LLM Applications via Multi-Agent Conversation", "Wu et al.", "programmable conversable-agent workflows", "AutoGen treats a workflow as a group chat whose members can be people, models, or tools, each with a defined responsibility.", "Design message schemas, routing, human approval, tool permissions, termination, retries, and trace storage; make each channel observable and testable.", "Represent conversations as event-driven graphs; analyze topology, scheduling, memory consistency, cascading failures, and evaluation of entire trajectories.", "user channel --> coordinator --> specialist/tool channels --> shared transcript --> result"],
  ["04-agents-and-protocols", "19-metagpt", "2308.00352", "MetaGPT: Meta Programming for Multi-Agent Collaborative Framework", "Hong et al.", "software-team roles and structured handoffs", "MetaGPT imitates a small software company: product, design, coding, and testing roles pass documents to one another.", "Use typed artifacts and acceptance criteria at handoffs; version prompts and outputs; compare the role pipeline with simpler workflows on quality, latency, and cost.", "Study standard operating procedures as coordination priors, information loss at interfaces, error propagation, organizational analogies, and benchmark external validity.", "requirement --> product spec --> design --> code --> tests --> review"],
  ["04-agents-and-protocols", "20-multi-agent-survey", "2402.01680", "Large Language Model based Multi-Agents: A Survey of Progress and Challenges", "Guo et al.", "the design space and open problems of LLM multi-agent systems", "A swarm is not magic multiplication: adding more agents creates specialization opportunities and also more chances for misunderstanding.", "Choose centralized, hierarchical, or peer-to-peer orchestration; define memory, message channels, budgets, failure containment, and a single-agent baseline.", "Develop hypotheses about diversity, communication bandwidth, consensus, emergent behavior, correlated failures, and scaling laws for coordination.", "agents + topology + channels + shared world --> coordination dynamics --> outcome"],
  ["04-agents-and-protocols", "21-interoperability", "2505.02279", "A Survey of Agent Interoperability Protocols: MCP, ACP, A2A, and ANP", "Ehtesham et al.", "standard interfaces for tools, agents, and networks", "MCP is like a standardized tool socket; A2A is like a work-order language between independent service teams.", "Use MCP for tool/resource access and A2A for delegated tasks; validate schemas, identity, authorization, consent, provenance, timeouts, and audit logs at every boundary.", "Compare JSON-RPC and HTTP interaction models, capability discovery, trust establishment, state machines, delegation semantics, threat models, and protocol composition.", "LLM host --> MCP tools and resources --> A2A agent delegation --> policy and audit"],

  ["05-small-business", "22-productivity", "2302.06590", "The Impact of AI on Developer Productivity: Evidence from GitHub Copilot", "Peng et al.", "controlled evidence about AI-assisted software-development speed", "Developers were randomly given access to an AI pair programmer or not; the assisted group completed a bounded coding task substantially faster on average.", "Pilot on representative maintenance tasks, randomize access where possible, measure completion time plus correctness and review effort, and segment by experience without treating one short task as universal proof.", "Inspect randomization, sample selection, censoring and completion-time analysis, heterogeneous effects, task realism, novelty effects, and external validity for long-lived repositories.", "developers randomly assigned --> Copilot or control --> coding task --> time + correctness"],
  ["05-small-business", "23-customer-support", "2304.11771", "Generative AI at Work", "Brynjolfsson, Li, and Raymond", "field evidence from AI-assisted customer support", "A conversational assistant gave support agents suggestions; average productivity rose, with larger gains for less-experienced workers.", "Start with assistive drafting and knowledge retrieval, preserve agent authority, measure resolution quality and customer outcomes, and watch for surveillance or deskilling harms.", "Analyze staggered deployment, causal identification, worker heterogeneity, knowledge diffusion, retention, customer sentiment, and transfer limits beyond the studied organization.", "customer --> worker + AI suggestions --> response --> resolution, quality, and learning metrics"]
];

const stageInfo = {
  "01-foundations": "How language models represent context, learn from text, and scale.",
  "02-building": "How useful systems retrieve knowledge, reason, align, adapt, and act.",
  "03-evaluation-and-code": "How to measure general capability and repository-level software work.",
  "04-agents-and-protocols": "How agents coordinate through roles, channels, MCP, and A2A.",
  "05-small-business": "What controlled and field studies say about business productivity."
};

for (const [stage] of papers) fs.mkdirSync(path.join(root, "tutorials", stage), { recursive: true });
fs.mkdirSync(path.join(root, "papers"), { recursive: true });
fs.mkdirSync(path.join(root, "references"), { recursive: true });

const diagram = (flow) => `\`\`\`mermaid\nflowchart LR\n  ${flow.split(" --> ").map((x, i, a) => i < a.length - 1 ? `${String.fromCharCode(65+i)}["${x.replaceAll('"', "'")}"] --> ${String.fromCharCode(66+i)}["${a[i+1].replaceAll('"', "'")}"]` : "").filter(Boolean).join("\n  ")}\n\`\`\``;

for (const [stage, slug, id, title, authors, topic, intuitive, practitioner, researcher, flow] of papers) {
  const body = `# ${title}\n\n> **Paper:** ${authors} · arXiv:${id} · [abstract](https://arxiv.org/abs/${id}) · [local PDF](../../papers/${id}.pdf)\n>\n> **Why it is here:** ${topic}. Read after the preceding items in the roadmap.\n\n## One-picture map\n\n${diagram(flow)}\n\n## Tutorial 1 — intuitive understanding\n\n${intuitive}\n\nAsk three questions while reading: What problem existed before this work? What changed? What new risk or limitation appeared? Explain the diagram aloud without technical vocabulary. If you can give a familiar-life example and one counterexample, the intuition is strong enough to continue.\n\n## Tutorial 2 — practitioner context\n\n${practitioner}\n\n### Build-and-test exercise\n\nCreate the smallest experiment that contrasts the paper's idea with a baseline. Write down the input, expected output, success metric, cost ceiling, and a failure taxonomy before running it. Keep model, prompt, data, code, and environment versions together in source control.\n\n### Production questions\n\n- What data crosses a trust boundary?\n- What happens on timeout, malformed output, or partial failure?\n- Which metric represents user value rather than benchmark convenience?\n- Can a person inspect, override, and audit the result?\n\n## Tutorial 3 — researcher depth\n\n${researcher}\n\nReconstruct one central table or figure before proposing an extension. Record the exact dataset split, statistical unit, random seeds, inference settings, uncertainty interval, and compute budget. Then change one assumption at a time. A useful research note separates **claim**, **evidence**, **assumption**, **alternative explanation**, and **next experiment**.\n\n### Mathematical lens\n\nTreat a model as a conditional distribution $p_\\theta(y\\mid x)$, an evaluation as an estimator over sampled tasks, and an agent as a policy acting on observations. Identify which variables are observed, hidden, controlled, and confounded in this paper. Use the [math bridge](../../references/math-bridge.md) whenever notation becomes the obstacle rather than the idea.\n\n## Reading protocol\n\n1. Read the abstract, introduction, and conclusion; write the claim in one sentence.\n2. Inspect every figure and table; state what comparison each supports.\n3. Read methods and evaluation; list assumptions and threats to validity.\n4. Complete the exercise and add a one-page research memo.\n\n## Checkpoint\n\nYou are ready to move on when you can teach the intuition in five minutes, implement or evaluate a toy version, and name at least two ways the main conclusion could fail to generalize.\n`;
  fs.writeFileSync(path.join(root, "tutorials", stage, `${slug}.md`), body);
}

const manifest = ["order,stage,slug,arxiv_id,title,authors,pdf_url,tutorial", ...papers.map((p, i) => `${i+1},${p[0]},${p[1]},${p[2]},\"${p[3].replaceAll('"','""')}\",\"${p[4]}\",https://arxiv.org/pdf/${p[2]},tutorials/${p[0]}/${p[1]}.md`)].join("\n") + "\n";
fs.writeFileSync(path.join(root, "manifest.csv"), manifest);

const stages = Object.entries(stageInfo).map(([stage, desc]) => {
  const rows = papers.filter(p => p[0] === stage).map((p, i) => `| ${papers.indexOf(p)+1} | [${p[3]}](tutorials/${stage}/${p[1]}.md) | arXiv:${p[2]} |`).join("\n");
  return `### ${stage}\n\n${desc}\n\n| Order | Guide | Source |\n|---:|---|---|\n${rows}`;
}).join("\n\n");

fs.writeFileSync(path.join(root, "README.md"), `# LLM learning repository\n\nA methodical path from non-technical intuition to practitioner competence and research literacy. The collection contains ${papers.length} primary papers in reading order. Every companion guide has three independent passes: intuitive, practitioner, and researcher.\n\n## How to use it\n\n1. Follow [ROADMAP.md](ROADMAP.md); do not try to read each PDF linearly on the first pass.\n2. Open a guide, complete Tutorial 1, then skim the linked paper.\n3. Return for Tutorial 2 and its build-and-test exercise.\n4. Use Tutorial 3 only after you can explain and test the core idea.\n5. Store notes with the templates in [references/research-notes-template.md](references/research-notes-template.md).\n\nPDFs live in \`papers/\`; metadata and canonical URLs live in [manifest.csv](manifest.csv). Re-download deterministically with \`node download-papers.mjs\`.\n\n## Curriculum\n\n${stages}\n\n## Scope and cautions\n\nThis is a curated foundation, not a claim that benchmark scores equal usefulness or that multi-agent systems always beat one good agent. MCP and A2A evolve as specifications, so the arXiv survey is paired with official live references. The business studies concern specific writing and support settings; use them as evidence for pilot design, not as guaranteed ROI for every small business.\n\n## Repository layout\n\n- \`papers/\`: downloaded arXiv PDFs\n- \`tutorials/\`: ordered three-level companion guides\n- \`references/\`: mathematics, experiments, protocols, glossary, and note templates\n- \`manifest.csv\`: machine-readable bibliography and paths\n- \`download-papers.mjs\`: checksum-friendly downloader\n- \`verify-repository.mjs\`: completeness and PDF signature checks\n`);

fs.writeFileSync(path.join(root, "ROADMAP.md"), `# Methodical learning roadmap\n\nPlan for 12 weeks at 6-8 hours per week. A faster reader can compress it, but preserve the order and checkpoints.\n\n| Weeks | Papers | Intuition outcome | Practitioner artifact | Research artifact |\n|---|---:|---|---|---|\n| 1-2 | 1-5 | Explain tokens, attention, pretraining, and scaling | Tiny attention notebook or spreadsheet; compute/data budget memo | Derive attention and fit a simple scaling curve |\n| 3-4 | 6-10 | Explain retrieval, prompting, alignment, adaptation, and tool use | Cited RAG prototype with eval set and bounded tool loop | Ablation plan separating retrieval, generator, and policy effects |\n| 5-6 | 11-13 | Explain why one score is insufficient | Scenario-by-metric evaluation matrix | Validity and uncertainty critique of one benchmark |\n| 7-8 | 14-16 | Explain code tests versus real repository work | Containerized code-agent evaluation on a small repo | Error taxonomy and benchmark-contamination analysis |\n| 9-10 | 17-21 | Explain roles, channels, swarms, MCP, and A2A | Two-agent workflow with typed messages, approval, and audit trail | Single-agent control, topology ablation, and threat model |\n| 11 | 22-23 | Explain measured productivity versus marketing claims | Small-business pilot design with baseline and stop criteria | Causal diagram and external-validity critique |\n| 12 | all | Teach the whole stack end to end | Capstone, evaluation report, and operating runbook | Reproducible research proposal with preregistered hypotheses |\n\n## Weekly rhythm\n\n- **Session A:** Tutorial 1, paper abstract/introduction/conclusion, five-minute teach-back.\n- **Session B:** Tutorial 2, key methods/results, smallest useful implementation.\n- **Session C:** Tutorial 3, equations/validity, reproduce one result or design an ablation.\n- **Review:** Update a concept map and an error log; revisit weak prerequisites.\n\n## Promotion gates\n\n### Intuition → practitioner\n\nYou can describe attention, RAG, evaluation, and an agent loop without jargon; distinguish a model from the system around it; and name one failure mode for each.\n\n### Practitioner → researcher\n\nYou can implement a baseline, version all inputs, choose outcome-aligned metrics, report uncertainty and cost, construct an error taxonomy, and explain why observed results may not be causal or generalizable.\n\n### Research-ready capstone\n\nBuild a small-business assistant that retrieves from an approved document set, calls one bounded tool through MCP, delegates one task through an A2A-style interface, and records a trace. Compare it with (1) no AI, (2) a single prompted model, and (3) the multi-component system. Measure quality, completion time, cost, unsafe attempts, human corrections, and failure recovery.\n`);
